# Generated by Django 4.2.23 on 2025-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='UnKnow', max_length=100),
            preserve_default=False,
        ),
    ]
